import { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => (
	<div>
		<Head>
			<title>Home | myconfig.store</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<main>
			<h1>Welcome to myconfig.store</h1>
		</main>
	</div>
)

export default Home
