import { Box, Heading } from "@chakra-ui/react"
import { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Home: NextPage = () => (
	<div>
		<Head>
			<title>Home | myconfig.store</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Box as="main" bg="brand.dark" w="100vw" h="100vh">
			<Heading fontWeight="black" color="brand.orange" textAlign="center">
				Welcome to myconfig.store
			</Heading>
		</Box>
	</div>
)

export default Home
