import { Box } from "@chakra-ui/react"
import { NextPage } from "next"
import Head from "next/head"
import React from "react"
import { DefaultNavbar } from "../components"

const Home: NextPage = () => (
	<div>
		<Head>
			<title>Home | myconfig.store</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<Box as="main" bg="brand.dark" w="100vw" h="100vh">
			<DefaultNavbar />
		</Box>
	</div>
)

export default Home
